name: Build and Test Release-R2R

on:
  push:
    tags: [ "build-*", "release-*" ]
  pull_request:
    tags: [ "build-*", "release-*" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release-R2R
    - name: Test
      run: dotnet test --no-restore --configuration Release-R2R --verbosity normal
